In [12]:
import numpy as np
import random

In [13]:
x = np.array([1, 4, 6])
y = np.array([4,7, 3])

In [14]:
x + y

array([ 5, 11,  9])

In [20]:
x = np.arange(10)

In [16]:
np.full([10,6], 5)

array([[5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5]])

In [24]:
random.shuffle(x)
x

array([1, 5, 3, 8, 4, 0, 7, 2, 6, 9])

In [28]:
np.random.random([11,9])

array([[0.1633297 , 0.71338899, 0.74981577, 0.97862913, 0.81386888,
        0.37821169, 0.94275127, 0.46165505, 0.00996127],
       [0.55104379, 0.36966846, 0.01326324, 0.07800145, 0.89136501,
        0.68104514, 0.16536401, 0.20916608, 0.10091273],
       [0.46537319, 0.58992373, 0.25937305, 0.63936805, 0.69090129,
        0.69515624, 0.84734636, 0.0686147 , 0.25277625],
       [0.72292263, 0.25045729, 0.89842488, 0.96050542, 0.67464003,
        0.6299653 , 0.1915031 , 0.25920918, 0.23584349],
       [0.37591502, 0.16360081, 0.17616588, 0.43342258, 0.22849012,
        0.00594461, 0.77521504, 0.49257156, 0.95494019],
       [0.90848349, 0.92155892, 0.76106406, 0.88048764, 0.47081532,
        0.09281607, 0.7418474 , 0.81642368, 0.42708141],
       [0.7614022 , 0.50965643, 0.64881759, 0.0364388 , 0.53686806,
        0.51295065, 0.53168172, 0.58873783, 0.13907019],
       [0.14153473, 0.69209442, 0.54224339, 0.20141862, 0.03228295,
        0.49453948, 0.41192623, 0.23471422, 0.63940005],
